### ISSUE TITLE
Endless entries in table "cf_staticfilecache" 

### ISSUE THREAD

**Issue by SventB** [lochmueller/staticfilecache#105]
I uncheck option "Cache page as static file" in page properties of a page (this page should not be cached as static file".
For this page, there's no static file generated and I see info "static cache disabled on page" in info module. That's correct so far.
But an entry in table "cf_staticfilecache" is generated, with expire timestamp 2145909600, every time, I reload this page in FE.
Also, there's an entry generated in table "tx_staticfilecache_queue".

- TYPO3 version: 8.7.19
- staticfilecache version: 6.1.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Windows 7

**Comment by lochmueller** [comment]
Hmm.... good point. Perhaps we should check this here: https://github.com/lochmueller/staticfilecache/blob/master/Classes/StaticFileCache.php#L155 or comare the DB entry with the current generated. the only reason why the DB entry is created and no file is the explanation for the backend. This should only one entry per URL.

Regards,
Tim

**Comment by lochmueller** [comment]
Hey @SventB 
Do you have some more tecnical information. I try to rebuild the problem... It is only possible to get new entries with the same identifier, if the expires of the old one is to old. E.g. If you set the Cache Time to 1 second, a request would create a new entries each second. Do you check the cache time? Do you use the Garbage Collection?
Regards,
Tim

**Comment by lochmueller** [comment]
Yes... I cannot rebuild you problem.

Furthermore. The Table "tx_staticfilecache_queue" is filled by the "QueueRepository". The repository is only called, if the Cache Backend remove (flush, flushByTags, garbageCollection & remove) cache entries and the Boost mode is enabled. That means... if you really get one DB entry in "tx_staticfilecache_queue" per Frontend request, then the request fire one of the clearCache events of the CachingFramework each request?!? That would be strange...

You have to debug into the problem (because I cannot rebuild the situation). Please check when and why the QueueRepository->addIdentifier method is called (this is the only method that add entries to "tx_staticfilecache_queue")

Regards,
Tim

**Comment by lochmueller** [comment]
Hey @SventB 
I close this issue. I need more information of the structure of your requests and the calling hooks. I think it is a configuration problem outside of the staticfilecache extension. If you have new/detailed information, feeel free to reopen the issue or create a new one.
Regards,
Tim
