### ISSUE TITLE
Always run Queue if called by the Hook

### ISSUE THREAD

**Issue by MartinH0** [lochmueller/staticfilecache#192]
### Describe the solution you'd like

Lets start with a Case.
(1) We have a big website
(2) We change content frequently

**Now out settings**:
(1) SFC Bootmode
(2) `staticfilecache:boostQueueRun 0 0` every 300s (5min)
(3) `staticfilecache:boostQueueCleanup` every 300s (5min)

**What we do now**:
(1) We change some content
(2) Pages are ending up in Queue
(3) We have to wait 5min untill it gets published.

Means the Site gets updated Timebased, even if the pages are getting pushed in the Queue Eventbased. (every 5 min + [time to regenerate])

### Describe alternatives you've considered
A much faster way to display the new page would be this:

Everytime a Page gets pushed to the Queue by the Hook (not by the `staticfilecache:flushCache` Cron/command!) will, after its finished, trigger the `staticfilecache:boostQueueRun 0 0` command.

**Now we do the same**:
(1) We change some content
(2) Pages are ending up in Queue
(3) `staticfilecache:boostQueueRun 0 0` gets triggered automatically
(4) We have to wait [time to regenerate] untill it gets published.

No matter what, this way its always faster up to date, is Event-Driven (not Time-Driven).

Even if we change something that affents 20-30 other sites it doesnt matter if they are getting re-rendered in 5 min or not, the server needs exactly the same time to do so, but if he starts earlier he finishes realier. If the command `staticfilecache:boostQueueRun 0 0` gets triggered more often in the meantime it doesnt matter.

**Comment by lochmueller** [comment]
hmm... i will check this for v11. Calling the CLI is a good point, because it doesn't block the execution of the backend extension, but there is no API to call CLI tasks directly.

**Comment by MK-42** [comment]
Can't scheduler tasks be marked as 'late' somehow? Maybe its possible to schedule the task for the next scheduler run (what depending on your cron-schedule calling the typo3 scheduler) might be as often as every minute.

**Comment by lochmueller** [comment]
@MK-42 
Which StaticFileCache Version do you use and which TYPO3 version? Of course a task should be markable as "run on next CLI". I don't understand your idea?

**Comment by MK-42** [comment]
I'm thinking hypothetically about this issue, as I'm quite new to sfc.
Thought the 5min limit was imposed by the frequency of a recurring scheduler task inside of typo3.
In that case the external cron could be set to invoke typo3s scheduler every minute, and sfc could mark the boostQueueRun task as `runOnNextCli`. Like that it would only be a one minute delay, without always running the task every minute.

If that is how it is working anyway - then sorry for the noise. Just getting my head around all this.
Is there any documentation on Boost-Mode btw?

**Comment by lochmueller** [comment]
No... the Boost Mode documenation is not realy exists ;) Feel free to contribute ;)

But SFC should not need to mark tasks as `runOnNextCli`. The easiest way is, that you configure crontab to `* * * * *` (it is recommended by the way) to trigger the scheduler. And if you really need a fast update of the page (I used SFC in many web projects and 5 minutes are always more then enough - furthermore the editor see always the TYPO3 output, so the editor do not know, that the content is only a few minutes later) you can change the SFC clear scheduler task also to `* * * * *`. So the update frequency is 1 minute.

I already write to @MartinH0 via slack. I don't know if the feature is usefull to rebuild/warumup caches on editor backend actions. Example: There are news records that are used on 6 pages. The editor write the article and save the article avery few minutes (because he/she want to avoid data losses), then every save action delete and recrawl the caches in the save action of the user. Best-case: Only a few seconds, worst case: Saveing content Element taks many minutes, becase https://docs.typo3.org/m/typo3/reference-tsconfig/master/en-us/PageTsconfig/TceMain.html#clearcachecmd = `all` or `pages` build the situation, that on EACH save extension of the editor in the backend the COMPLETE frontend cache is rebuild IN THE save request of the backend user. This is not really helpfull and case many problems.

So the scheduler is the best solution. If 5 min are to long, set this to 1 Minute. If 1 Minute is to long, I think a custom implementation is the best way, to avoid conflicts with general TYPO3 functions like `clearcachecmd`.

Regards,
Tim

**Comment by MartinH0** [comment]
The point of this Feature Request was to not rely on a "Time-Based" update of the Cache-Generation but more on a Eventbased update to make changes apply immediately.
5 mins delay are ok for most of the Projects but on some you just want to make everything you do to be done right then, when you do it.

Like the example I made above:
if you change a page whcih will affect 20 other pages its better to **start** generating the new cache immediately then 5 mins later. Becasue it have to be done anyway but if you start faster you finish faster.

Other things to clearify:

1. the main TYPO3 cron always should be set to `* * * * *`
2. you can decide how often you want to run the SFC Cron in the backend.
3. setting the Cron to every min may reduces the difference but if not solving the problem by its roots. Its still Time-Based "regeneration" of the cache an not Event-Based.

Therefor this request was created but if this does not belong to this extension it can be closed.
Would be sad as this (at least I think) is the way a cache should be regenerated.

**Comment by lochmueller** [comment]
Yes. If there is a smart way to call CLI tasks from the backend web request, I will integrate it. I will check this for the next releases...

**Comment by lochmueller** [comment]
I checked this... there is no smart API to call CLI scripts inside a WebRequest in the backend. So I will drop this feature. Perhaps we will reopen it in the feature. For more information:The API for running the queue is defined here:
- EXT:staticfilecache/Classes/Command/BoostQueueCommand.php
Feel free to create your one hook and use it in your project (perhaps contribute it as pull request).
