### ISSUE TITLE
Button to Hard-Flush Cache

### ISSUE THREAD

**Issue by MartinH0** [lochmueller/staticfilecache#197]
## Feature Request

**Describe the solution you'd like**
A button registered between the standard Cache-Flush buttons of TYPO3 to hard-flush the Cache of SFC and truncate all necessary DB-Tables

It could be look like this:
![SFC hard wipe cache](https://user-images.githubusercontent.com/17692860/66474295-4b89f280-ea91-11e9-88ff-f52b572b3943.PNG)

### What should it do:

Delete these folders:
`typo3temp/tx_staticfilecache`

Truncate these DB-Tables:
`cf_staticfilecache` or `sfc_staticfilecache`,
`cf_staticfilecache_tags` or `sfc_staticfilecache_tags`,
`tx_staticfilecache_queue`

### Why is this good?
- After a Update/Upgrade you may want to clean all Caches no matter if in Bootst mode or not.
- if something is not working as expected, maybe a previously created Cache is causing this issue
- this is 1000 times better then deleting the folder manually because maybe someone forget about truncating the right DB-tables

**Comment by lochmueller** [comment]
Hey @MartinH0 
there is already a command controller to flush the cache. It is trongly recommend NOT delete the full caches so easily by a editor. I moved the flush to a service class so you can flush the cache easily by yourself (feel free to create the clear cache by yourself): 
```\TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\SFC\Staticfilecache\Service\CacheService::class)->flush(true);```
Notice: The "typo3temp/tx_staticfilecache" folder should never be deleted (only the subfolders), because many people mount the folder to RAM and the extension should not drop the main folder.
Regards,
Tim
