### ISSUE TITLE
Weired Htaccess rewrite rule expires value.

### ISSUE THREAD

**Issue by s-leger** [lochmueller/staticfilecache#203]
## Bug Report
Weired Htaccess rewrite rule expires value.

**Current Behavior**
```
<IfModule mod_rewrite.c>
	RewriteEngine On
	RewriteCond %{ENV:REDIRECT_STATUS} ^$
	RewriteRule .* - [F,L]

	RewriteCond % >19700102010000
	RewriteRule ^.*$ /index.php
</IfModule>
```
get negative $realLifetime in StaticFileBackend line 47. Suspect a unix timestamp overflow?

**Expected behavior/output**
RewriteCond % > now + timeout

**Environment**
- TYPO3 version(s): 8.7.28
- staticfilecache version: 9.0.0
- realurl 2.5.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Mint 19

**Possible Solution**

**Additional context**
Page cache forced through "Force the static cache generation (!!!)"
Unable to identify the source of "config.no_cache = 1" while not set in config at all, but looks like it occurs soon in the page generation process.

**Comment by lochmueller** [comment]
There is also a missing "{TIME}" in your output. But....

This is already fixed in the current release. The expires timestamp always include the current time:
https://github.com/lochmueller/staticfilecache/blob/master/Classes/Generator/HtaccessGenerator.php#L50
there is a "TIME" variable that output the "{TIME}" in the template:
https://github.com/lochmueller/staticfilecache/blob/master/Classes/Generator/HtaccessGenerator.php#L49
https://github.com/lochmueller/staticfilecache/blob/master/Resources/Private/Templates/Htaccess.html#L18

I close this issue... please disable this feature and use it, if your are working with StaticFileCache >= 10.0.1.
There will be no releases for old extension branches anymore...

**Comment by lochmueller** [comment]
Note: It is strongly recommended NOT using "Force the static cache generation (!!!)" options. This could cause several problems.
