### ISSUE TITLE
CookieService not working properly

### ISSUE THREAD

**Issue by MartinH0** [lochmueller/staticfilecache#204]
**Expected behavior/output**
Since I changed the Cookie domain to `/\.(domain\.de)|(domain\.ch)` (which is TYPO3 Valide it does not work with SFC. Error means its not matching the Domain but I'm on `https://www.domain.de`

In the Error it somehow shows me my pattern a bit different:
`at TYPO3\CMS\Core\Error\ErrorHandler->handleError(2, 'preg_match(): No ending delimiter \'/\' found', '/var/www/vhosts/domain.de/httpdocs/typo3/typo3conf/ext/staticfilecache/Classes/Service/CookieService.php', 53, array('result' => '', 'cookieDomain' => '/\\.(domain\\.de)|(domain\\.ch)', 'match' => array()))`

So its states its `/\\.(domain\\.de)|(domain\\.ch)` but in fact it is `/\.(domain\.de)|(domain\.ch)`

**Environment**
- TYPO3 version(s): 10.1.0
- staticfilecache version: 10.0.0-dev

![screencapture-hotmann-de-typo3-2019-10-17-23_05_23](https://user-images.githubusercontent.com/17692860/67048958-7204f900-f135-11e9-8aed-c2be5d894fde.png)

**Comment by MartinH0** [comment]
Solved that particular problem by adding a trailing slash.

Also modified it overall.
Now it looks like this:

`/\.domain.(de|ch)/`

This bug is solved now

**Comment by lochmueller** [comment]
This is no bug, more a miss configuration. The core throw no error, because the error is ignored with a "@" sign:
https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Classes/Authentication/AbstractUserAuthentication.php#L483
If StaticFileCache also add a "@" you don't get the information that the configuration is wrong (only in the log). So I will keep the current code.
