### ISSUE TITLE
htaccess RewriteCond %{TIME}

### ISSUE THREAD

**Issue by SventB** [lochmueller/staticfilecache#208]
TYPO3 version 8
EXT.staticfilecache version 9.0.0

I have problems with the htaccess file which is added in the folder besides the static html file. The Fluid template contains this:

```
RewriteCond %{ENV:REDIRECT_STATUS} ^$
RewriteRule .* - [F,L]
RewriteCond %<![CDATA[{TIME}]]> ><f:format.date format="YmdHis">@{expires}</f:format.date>
RewriteRule ^.*$ /index.php
```
This results in 

```
RewriteCond %{ENV:REDIRECT_STATUS} ^$
RewriteRule .* - [F,L]
RewriteCond % >20191024191244
RewriteRule ^.*$ /index.php
```

{TIME} is missing!

A user says escaping with CDATA doesn't work in TYPO3 8.7: https://stackoverflow.com/questions/17696105/how-to-escape-curly-bracket-in-typo3-fluid-template

This fixes the problem:

```
RewriteCond %{<f:format.raw>TIME</f:format.raw>} ><f:format.date format="YmdHis">@{expires}</f:format.date>
```

**Comment by lochmueller** [comment]
Hey @SventB 
thanks for reporting. This problem is already fixed in version 10.x.
I added a `TIME` variable to the fluid variables so the variable is replaced with `{TIME}`:
https://github.com/lochmueller/staticfilecache/blob/master/Classes/Generator/HtaccessGenerator.php#L49
There will no bugfix releases for old versions, so I close this issue.

If you cannot upgrade I suggest a composer patch that add this line in the right place, since a update is possible.

Regards,
Tim

**Comment by SventB** [comment]
All right :) 
I will overwrite the Fluid template.
