### ISSUE TITLE
Sitemaps are getting "Fake Cached"

### ISSUE THREAD

**Issue by MartinH0** [lochmueller/staticfilecache#219]
## Bug Report

I redirected `/sitemap.xml` internaly to `/?type=1533906435` with my htacces.
Works perfectly so far. All sitemaps are getting displayed perfectly.

**Current Behavior**
Sitemaps ( /sitemap.xml ) are getting shown as Rootpages.
Also they do exist on the FileServer (change got created) but they are not getting delivered by SFC.
I dont want them to getting delivered by SFC but just not display them as cached in the Backend.
![SFC sitemap](https://user-images.githubusercontent.com/17692860/68722795-e4db8580-05b6-11ea-9bfb-896fc75b6b91.PNG)

This also applys to `/robots.txt` (if not statically but generated by TYPO3)

**Expected behavior/output**

**Environment**
- TYPO3 version(s): 9.5.11 / 10.1.0
- staticfilecache version: 10.1.0

**Comment by lochmueller** [comment]
Question before checking. Do you redirect `sitemap.xml` or do ypu use the routing of TYPO3 9?

**Comment by MartinH0** [comment]
I redirect with htacces AND use routing enhancer from TYPO3 9.

With just one of these Configs I do not get the result I want, with both I do.

My config.yaml contains this:

```
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      sitemap.xml: 1533906435
```

In my htaccess I added this:

```
# Sitemap.xml
RewriteRule (.*)sitemap\.xml$ $1?type=1533906435&sitemap=pages&cHash=[cHash] [L]
```

(**`[cHash]`** standas for my cHash)

**Comment by lochmueller** [comment]
I don't understand why you skip the Index Sitemap be redirecting directly on und pages sitemap? Whats wrong with the sitemap overview? but this is a other point.
I will check this. But please keep in mind, that I will check this without the RewriteRule and the real sitemap.xml (as overview) and e.g. pages/sitemap.xml (as Pages XML sitemap), because in this case both should be cachable.
Regards,
Tim

**Comment by lochmueller** [comment]
Hey @MartinH0 
I added a little bit of documenation and test the caching. The entries a valid in my case. I add the routing information to the documentation. I suggest to drop the Redirect, because the routing can avoid the cHash and create also valid cache entries for subsites (XML record sitemaps). Furthermore the XML Index Sitemap is very usefull to get a clean overrview.
Regards,
Tim
