### ISSUE TITLE
Respect options, which are configured in EXT:scheduler

### ISSUE THREAD

**Issue by koehnlein** [lochmueller/staticfilecache#238]
## Bug Report

**Current Behavior**
I'm using your extension in a TYPO3 8 LTS installation. So I cannot update to the latest version of your extension, but hope you will provide an update for version 9 of your extension.

The problem is, that the options, configured in scheduler, are not passed to the BoostQueueRunCommand but `stop-processing-after` and `limit-items` are always set to "0"

![Bildschirmfoto 2020-02-05 um 16 25 18](https://user-images.githubusercontent.com/16088567/73856401-b24bcc80-4835-11ea-8e1c-2a7c07ab8f00.png)

**Expected behavior/output**

I expect the values, I set in scheduler, to be respected in BoostQueueRunCommand

**Environment**
- TYPO3 version(s): 8.7.*
- staticfilecache version: 9.0.0

**Possible Solution**
The solution would be finished, but I cannot provide a merge request, because you do not have a v9 branch: https://github.com/lochmueller/staticfilecache/compare/master...koehnlein:feature/v9/scheduler-options

**Comment by lochmueller** [comment]
You are right: https://symfony.com/doc/current/console/input.html 
Both tasks should use options instead of arguments: https://github.com/lochmueller/staticfilecache/tree/master/Classes/Command ... I will check this in the next week and will fix it for the current version. There will be no bugfix version for old StaticFileCache versions.
Thanks for reporting this problem.
Regards,
Tim
