### ISSUE TITLE
timestamp signature configuration missing

### ISSUE THREAD

**Issue by paul-siteway** [lochmueller/staticfilecache#250]
## Bug Report

**Current Behavior**
"Show generation timestamp signature" Checkbox is missing
![Bildschirmfoto 2020-04-17 um 15 52 29](https://user-images.githubusercontent.com/3603487/79576593-d80e1100-80c3-11ea-8730-c3aedecfea93.png)

**Expected behavior/output**
"Show generation timestamp signature" Checkbox is displayed
![Bildschirmfoto 2020-04-17 um 15 52 43](https://user-images.githubusercontent.com/3603487/79576547-bf9df680-80c3-11ea-9cbb-227bec520e22.png)

**Environment**
- TYPO3 version(s): 9.5.13
- staticfilecache version: 11.0.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Possible Solution**

**Additional context**

**Comment by lochmueller** [comment]
Hey @paul-siteway ,
the option is called "Debug Headers" because I don't want to modify the content anymore, because this will break JSON output and other non-html markups. So there are "Debug headers" with more tecnical information, if you enable the checkbox.

![Bildschirmfoto 2020-04-17 um 16 23 44](https://user-images.githubusercontent.com/3907126/79579516-f5dd7500-80c7-11ea-80f9-fba109555270.png)

Regards,
Tim

**Comment by paul-siteway** [comment]
Ok. You might want to update the Docs then: https://github.com/lochmueller/staticfilecache/blob/master/Documentation/Configuration/Global.rst

**Comment by lochmueller** [comment]
Thanks for the hint. I dropped the documentation and add a link to the current configuration file.
