### ISSUE TITLE
Rebuild cache after flushing?

### ISSUE THREAD

**Issue by j4k3** [lochmueller/staticfilecache#268]
## Bug Report

**Current Behavior**
After forcefully flushing the Cache, the BoostQueue runner does not rebuild it.

**Expected behavior/output**
I have an installation that mostly consists of a big calendar with many list-based pages that basically all need to be rebuilt daily. I want my server to flush these pages nightly and then rebuild them all. Instead the BoostQueue seems to think it has nothing to do? 
By the way, my tx_staticfilecache_queue is bloated, once more. 5738 distinct identifier entries at 59761 total entries with up to 127 duplicates with the same identifier.

**Environment**
- TYPO3 version(s): 9.5.20
- staticfilecache version: 11.1.7
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: debian-based linux distro

**Possible Solution**
Refill tx_staticfilecache_queue with the contents of cf_staticfilecache after flushing.

**Comment by lochmueller** [comment]
Hey @j4k3 

how do you rebuild the ccache nightly? I you are using clearCacheAtMidnight the Queue is not filled, because the "clearCacheAtMidnight" option do NONT clear the cache at midnight. Instead the cache entries got a lifetime that is nnext midnight. Perhaps that is the reason, why the queue is empty?

"By the way, my tx_staticfilecache_queue is bloated, once more. 5738 distinct identifier entries at 59761 total entries with up to 127 duplicates with the same identifier." This problem was fixed here I think: https://github.com/lochmueller/staticfilecache/commit/708b5225d686b1173e18b96dd0a953099fd1bd62 Is already part of the 12.x release. Side note: No new TYPO3 v9 compatible releases in the feature.

"Refill tx_staticfilecache_queue with the contents of cf_staticfilecache after flushing." This is not possible. We have to keep TYPO3 instances with multiple websites and different configurations in mind.

Best regards,
Tim

**Comment by j4k3** [comment]
"how do you rebuild the ccache nightly?"
I've created a scheduler task that clears the cache at 00:15 using staticfilecache:flushCache --force-boost-mode-flush

"This is not possible. We have to keep TYPO3 instances with multiple websites and different configurations in mind."
What do you mean? All the URLs to refill the queue with are right in cf_staticfilecache, why not grab and copy them when forcefully flushing the cache, preferably filtered to have no duplicates?

**Comment by lochmueller** [comment]
Hey @j4k3 
the cf_ tables are the result of  the caching framework of the Core. I try to use only tthe caching framework API to avoid inconsistency in the cache.
Could I ask why you drop the complete cache at night? I don't know the usecase for this? Why do nont use the selectiv options of TYPO3 and TYPO3 Cachig Framework too delete the cache only whe needed?
Regards,
Tim

**Comment by j4k3** [comment]
Hey @lochmueller,

I clear the cache because of many edge cases that unfortunally occur on a frequent base in all of our bigger projects.
In general, the problem is simply, that for everything that isn't set up metaiculously, changes in the backend don't show up immediately. It unfortunately seems to be impossible to explain to our customers ant their editors why thats the case and that it isn't neccessarily an error but a feature.
I agree that it's suboptimal to rebuild the whole cache at night, but I don't know how else to reliably update the generated cache contents, especially regarding the following cases:

One problem, for example, is that I just cant figure out how to clear the caches of subpages when content is modified on a parent page. I would expect TYPO3 to understand its own concepts of inheriting content to subpages but that does not seem to be the case.

Another problem occurs when editors change, delete or create pages that appear in the navigation on many or all pages of the installation. How do I set up the frontend cache to regenerate a whole site when the contents of a navigation change?

But the biggest problem is in my own extensions when they reach a certain complexity. I have, for example, a page that consists mostly of a large event calendar. About 100 people have access to an event editor in the frontend. For performance reasons I hold the paginated List pages in the FrontendCache. Adding a CacheTag to the page would mean these pages would be reprocessed every single time someone modifies an event.

**Comment by lochmueller** [comment]
Hey @j4k3 
I will think about this... your three problems sound like missconfiguration of the caching framework. Clearing the cache to a fixed time is always not a very good idea, because there should be some changes (editor changes, import data...) that should trigger clear cache.

My ideas for this problems (all not related to SFC): 
- First problem: just add the "pageId_XX" XX = parent page pid
- Second problem: Us a Menu building that add the pageId_XX tags from all pages that are part of the menu. Furthermore check the TYPO3 logic for clear cache for navigations.
- Third problem: Yes. Perhaps a more selektiv caching logic in the complex extension.

Regards,
Tim

**Comment by j4k3** [comment]
Hey @lochmueller,

thanks for the reply. Just to reemphasize, we have some projects with a good dozen of backend editors that expect pages to change the second they've edited the content. My current approach for this is to disable the frontend cache via a condition, like so 

    [globalVar = TSFE:beUserLogin = 1]
      config.no_cache = 1
    [global]

and that works for most cases. It unfortunately seems to be impossible to explain to them that in some cases older content retaining on the page is actually a feature, not a bug. And explaining to them how to use the cache flush buttons is completely impossible, too. The nightly flush has stopped the constant calls and "bug reports" but it unfortunately doesn't rebuild the cache, therefor making the cache more or less useless.


> First problem: just add the "pageId_XX" XX = parent page pid
This will only work for a given point in time. It will not work with newly created pages and the whole hierarchical tree of subpages would have to be updated with cahnges on a page. I thought about implementing a Hook for processDatamap_afterAllOperations but I didn't find the time yet to test this. 

> Second problem: Us a Menu building that add the pageId_XX tags from all pages that are part of the menu. Furthermore check the TYPO3 logic for clear cache for navigations.
Can you give me a better pointer for what you mean? Many of our older projects still use the TypoScript TMENU navigation generation, is there a way to generate CacheTags in TypoScript? 

> Third problem: Yes. Perhaps a more selektiv caching logic in the complex extension.
My problem here is, that adding Cache Tags will always flush a page with all possible parameter combinations. The calendar page generates a few hundred paginated pages of event lists. Every change on an event would require all these pages to be rebuilt. The nightly rebuild is my current best shot at keeping the server load within my hosters restrictions...


So, I'm not sure if these problems all actually have an easy solution that I just can't see. What I don't understand is why there isn't a way to manually, immediately flush the staticfile cotent, while retaining the queue content. So that when the cache is flushed manually, the outdated staticfilecache content is immediately deleted, but the queue is still there and the boostQueue runner can get right back to rebuilding the pages.
