### ISSUE TITLE
hashUriInCache implementation incomplete

### ISSUE THREAD

**Issue by infabo** [lochmueller/staticfilecache#271]
## Bug Report

**Current Behavior**
Enabling `hashUriInCache` breaks the site, because StaticFileBackend tries to access not available data.

https://github.com/lochmueller/staticfilecache/blob/f7fa0e214779e5f5d9ebcc5ffc16e3c5758d21c5/Classes/Cache/StaticFileBackend.php#L297

**Expected behavior/output**
When `hashUriInCache` is enabled, it should store a field `url` in the cache-record, so the url is resolvable on fetching the cache-record again.

**Environment**
- TYPO3 version(s): 9.2.21
- staticfilecache version: 11.1.7
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux

**Possible Solution**
Finish `hashUriInCache` feature.

Maybe set `url` here: https://github.com/lochmueller/staticfilecache/blob/f7fa0e214779e5f5d9ebcc5ffc16e3c5758d21c5/Classes/Cache/StaticFileBackend.php#L50

**Additional context**
Add any other context about the problem here

**Comment by lochmueller** [comment]
Hey @infabo 
I think this problem is fixed with the last commit of this patch: https://github.com/lochmueller/staticfilecache/commit/d1380df37fb3452bfb86f22d3e84e49a80a0fa3b
I close this issue... if there are still problems, please create a new issue.
I will release a new version shortly...
Regards,
Tim
