### ISSUE TITLE
Backport: Sitemap.xml has wrong Content-Type if fallback middleware is enabled

### ISSUE THREAD

**Issue by thommyhh** [lochmueller/staticfilecache#286]
## Bug Report

Please backport the fix from #278 to 11.x, which still has support for TYPO3 CMS 9.
As CMS 9 is still supported, I think dropping support in such an important extension as this is kind of mean.

**Comment by lochmueller** [comment]
Hey @thommyhh 

thanks for the report. TYO3 CMS 9 is in the "prioritoy bugfix" step of the software lifetime. I want to use more modern integration and drop v9 support. Feel free to fork the repo and add the patch for your installation. Sorry, but I cannot offer support for old versions in my freetime and there will be no new versions for old extension releases (except security related problems).

I close this issue, because it is fixed in the current version.

Regards,
Tim
