### ISSUE TITLE
Add path to the missing htaccess message

### ISSUE THREAD

**Issue by lochmueller** [lochmueller/staticfilecache#297]
Add more details to the error in the backend, that the htaccess file is missing. Add the path that is checked.

**Comment by ursbraem** [comment]
As far as I understand now, this message is only informative. The BE module can't find the .htaccess. That's more a nice to have – it's the Frontend that needs it. Correct?

In that case, instead of 

> We couldn't find the StaticFileCache configuration in the htaccess file. Perhaps you configure the rules in the Webserver, you do not use an Apache webserver or you are using composer packages like typo3-secure-web (move the public folder away). But: In most cases the configuration is missing!! (Note: We search for "SFC_FULLPATH" in this file)

you could write the following message:

The backend module couldn't find the StaticFileCache configuration in the htaccess file at `{path}/.htaccess`. Perhaps you configure the rules in the Webserver, you do not use an Apache webserver or you are using composer packages like typo3-secure-web (move the public folder away). But: In most cases the configuration is missing (note: We search for "SFC_FULLPATH" in the .htaccess file). This check is informative though. To make sure staticfilecache works, enable `basic.debugHeaders` and check for the `x-sfc` headers on your pages. `x-sfc: TYPO3 - already in cache` means that the .htaccess rewrite works as expected.
