### ISSUE TITLE
An access protected page (or a page with access protected CE) should not be cached statically

### ISSUE THREAD

**Issue by foobar13372** [lochmueller/staticfilecache#326]
Be logged out.
Have a page with any access-controlled content (any group) or the page itself (e.g. "only show when logged out").
Visit this page.
The page gets cached statically.
Login.
You see the static cached page.

The check whether a page can be cached should not only consider whether the current user has a session, but also whether the current page itself already comes with any access modifiers (which declares it dynamic and thus non-cachable by defintion).

**Comment by lochmueller** [comment]
The part `You see the static cached page.` should not possible, because if you have a active user session, there should also a "staticfilecache" cookie. And there is a condition that check if the cookie exists:

RewriteCond %{HTTP_COOKIE} !staticfilecache [NC]

Could you check, if there is a cookie called "staticfilecache" after the "Login" step and check if the last request is send to the server? Perhaps you send the first page with Expires headers and the request after the login is NOT send to the server?!

Regards,
Tim

**Comment by lochmueller** [comment]
I close this bug. No feedback for open questions... Feel free to create a new issue or reopen it with more details.
