### ISSUE TITLE
easy use w/ `helhum/typo3-secure-web`

### ISSUE THREAD

**Issue by xerc** [lochmueller/staticfilecache#379]
if `helhum/typo3-secure-web` is used the `typo3temp` folder is within a sub-folder
ref. https://github.com/helhum/typo3-secure-web#configuration
> ln -s ../../{root-dir}/typo3temp/tx_staticfilecache {web-dir}/typo3temp/tx_staticfilecache

**Comment by lochmueller** [comment]
Hey @xerc 

I would close this issue. The next release of EXT:staticfilecache will be for TYPO3 v11 & v12. Both version support the new composer-installer that handle the Public-Asset split (for v11 you have to install this version manually "composer require typo3/cms-composer-installers v4.0.0-RC1"). In my opinion "the core way" with cm/s-composer-installer is much better then secure-web-way, because there are no "two main folder". All extensions keep in the vendor-dir and only Resources/Public are linked in the document root. So EXT:staticfilecache do not need any special handling for the new cm/s-composer-installer.

Your symlink idea is also good. I think EXT:staticfilecache do not delete the main folder in typo3temp so it is possible to set this folder as symlink.

Regards,
Tim

**Comment by helhum** [comment]
> I would close this issue. The next release of EXT:staticfilecache will be for TYPO3 v11 & v12. 

Even with TYPO3 12, the correct folder to publish temporary public assets is `typo3temp/assets/`.
So I suggest to update the default folder of staticfilecache to `typo3temp/assets/tx_staticfilecache`

**Comment by lochmueller** [comment]
Hey @helhum 
thanks for your thoughts... I added the "assets" to the default path for the next version.
Regards,
Tim
