### ISSUE TITLE
[TASK] avoid use statements inside ext_tables.php / ext_localconf.php and Configuration/TCA

### ISSUE THREAD

**Issue by AndreasA** [lochmueller/staticfilecache#38]
Probably not that important as currently there is only a use statement inside "Configuration/TCA/Overrides" which shouldn't be a problem as those files are required / included per file.
However, it is probably best to still avoid doing so and only use those for classes in case this might change in the future.
For ext_localconf.php / ext_tables.php it is required to not have a "use" statement there as those files are concatenated and so one might run into fatal errors if multiple extensions use them.

**Comment by lochmueller** [comment]
Hey @AndreasA 
for ext_* files you are right (there are no use imports at the moment). 

I don't found any information that the Configuration/TCA files are also concatenated in the future. Also I do not think it will happen, because it is very "bad" programming style to concatenate foreign source code files and the current solution (loading and caching of the TCA) is the better way.

Regards,
Tim

**Comment by AndreasA** [comment]
Probably true. So I will close this.
