### ISSUE TITLE
Parse Error: Classes/Service/CookieService.php

### ISSUE THREAD

**Issue by maslme** [lochmueller/staticfilecache#400]
## Bug Report

**Current Behavior**
Frontend crashed with a 503 error -> ParseError 
syntax error, unexpected 'private' (T_PRIVATE), expecting variable (T_VARIABLE)

in [...]/staticfilecache/Classes/Service/CookieService.php line 22

**Expected behavior/output**
No Error ;-)

**Environment**
- TYPO3 version(s): 11.5.32 non composer mode
- staticfilecache version: 13.1.3
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- PHP: 8.0.30

**Comment by lochmueller** [comment]
Hey @maslme 
the affected line ( https://github.com/lochmueller/staticfilecache/blob/13.1.3/Classes/Service/CookieService.php#L22 ) use constructor promotion https://wiki.php.net/rfc/constructor_promotion / https://php.watch/versions/8.0/constructor-property-promotion that is available since PHP 8.0. Are you really sure, that you execute the script with PHP 8.0.x? The error message sounds like, that class constructor promotion is not allowed/possible?!?!
Regards,
Tim

**Comment by maslme** [comment]
Thanks @lochmueller for your quick reply.
Yes, you're right - upon closer inspection, I found that the error only occurs when I access the site through an alternative domain (which was still running on PHP 7.4), while on the main domain running PHP 8.0.30, everything worked fine.
