### ISSUE TITLE
boost mode status

### ISSUE THREAD

**Issue by Nemo64** [lochmueller/staticfilecache#66]
So I tried to figure out boost mode and am curious. What is the status on boost mode? It doesn't look completely developed. The lack of documentation also seems to indicate that.

So I figured I have to schedule runcacheboostqueue and cleanupcacheboostqueue. That will automatically update pages that are changed though the backend. That works great. 👍 

But than I looked at the `StaticFileBackend`. So `remove` will schedule an update of the page... So far so good. But calling `flush` will schedule only expired entries for an update and calling `collectGarbage` will actually remove all outdated without scheduling anything. I would expect flush to schedule everything and collectGarbage to schedule only expired entries.

And there is more which I haven't tested but just figure though the source: If a page gets unavailable, the update will have a `!= 200` result and try to remove the entry from  the cache ~ which should schedule it again. So that should result in an endless retry cycle if i'm not overlooking something.

So I figure that it can be used but doesn't work as advertised since collecting cache garbage (which should definitely be done) will make the cache cold without scheduling a warmup.

Did I figure that out correctly? Do you need help or do you want to continue develop the boost mode?

**Comment by lochmueller** [comment]
Hey @Nemo64,

first step. The queue worker set this constant:
https://github.com/lochmueller/staticfilecache/blob/master/Classes/Service/QueueService.php#L33

and in the StaticFIleBackend this constant is checked:
https://github.com/lochmueller/staticfilecache/blob/f78196ed09c71bf2ddcf7918e5aa8ef005b5a77f/Classes/Cache/StaticFileBackend.php#L326

So the "isBoostMode" is false, if the QueueService run throuh the queue entries and wrong entries are removed from the Cache without adding it to the queue again (so there should be no endless loop).

In general the boost mode is ready and works on some production systems. If the boost mode is active, alls caching functions that drop data, should not remove any information of the parent-cache backend or of the files and just add the URIs to the queue. Could you send me the line, where the problem is?

Please send me some links to the could, where the problems are, so I can check this...

Regards & have a nice weekend,
Tim

**Comment by Nemo64** [comment]
Thanks for the reply. I have totally overlooked the constant.

Ok but my concerns are about this here:
https://github.com/lochmueller/staticfilecache/blob/671d8d7a700663caff5eb84c1e4ac2d636ea9fc5/Classes/Cache/StaticFileBackend.php#L154
So a flush cache in backend only queues outdated pages.

But there is also this: https://github.com/lochmueller/staticfilecache/blob/671d8d7a700663caff5eb84c1e4ac2d636ea9fc5/Classes/Cache/StaticFileBackend.php#L212
So a garbage collect will do just that. Outdated pages get removed and there is no queue I can see.

**Comment by lochmueller** [comment]
Hey @Nemo64 
"So a flush cache in backend only queues outdated pages." This is right and part of the concept. There is no "delete all files" anymore. Alle "delete" operations are added to the queue only. Even the "flush all" option. Do you think the BE function should delete the complete cache? Or shoud we add a new "Delete Boost Mode cache" (with red icon) to the cache options, if the boost mode is enable?

The garbage collection collect pages that are realy outdated. You have to split... in the Boost-Mode there are pages that are not "up-2-date" for a several minutes (untill the scheduler work on the queue) and there are pages, that are outdated. The "outdated" one are deleted directly, because I do not know if there are critical parts on the next hit (example "clearCacheAtMidnight"). I think this was the reason.

Note: This are no "hard facts" or API requirements. The boost mode is "my own" interpration... I don't know if there are logical problems ;) So... please send me some feedback, if the explaination make sense ;)

Regards,
Tim

**Comment by Nemo64** [comment]
Well the problem with "flush all caches" is. If you change the layout of the page, then there is no way to schedule all pages for an update. Imo, there should be a way to schedule all pages for an update. And intuitively, that is the flush all caches button in backend... Or the command line during deployment.

Basically, flush all does what garbage collect should do and garbage collect does break the concept.

Also i think there should always be a garbage collect job to continuously update all pages. Otherwise functions like news "only show current news" would not work without someone pressing flush cache at the right time.

**Comment by lochmueller** [comment]
Hey @Nemo64 
please feel free to add your fixes/version as pull request. Please try to split different function separate pull requests, so I can manage the merge in the right way.

Otherwise I will check this in the  next days/weeks also again...

Regards,
Tim

**Comment by lochmueller** [comment]
Hey @Nemo64 
I checkged the handling of the two functions in the current master.
Please create new issues, if there are any open topics related to this change.
Regards,
Tim
